# Generated by Django 5.0.2 on 2024-03-29 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='gpa',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='military_service_status',
            field=models.CharField(choices=[('EP', 'Education Pardon'), ('P', 'Passed'), ('E', 'Exempted')], default='EP', max_length=2),
        ),
    ]
