# Generated by Django 4.2 on 2024-03-25 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='educationalassistant',
            name='department',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='past_courses',
        ),
        migrations.AlterField(
            model_name='student',
            name='entry_semester',
            field=models.CharField(max_length=100),
        ),
    ]
