# Generated by Django 4.2 on 2024-04-10 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='military_service_status',
            field=models.CharField(choices=[('EP', 'Education Pardon'), ('P', 'Passed'), ('E', 'Exempted'), ('F', 'Finished')], default='EP', max_length=2),
        ),
    ]
