# Generated by Django 4.2 on 2024-04-02 17:16

import accounts.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_number',
            field=models.PositiveIntegerField(unique=True, validators=[accounts.validators.validate_eight_digit_username]),
        ),
    ]
