# Generated by Django 4.2 on 2024-04-11 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='gpa',
            new_name='gpa_student',
        ),
    ]
