# Generated by Django 4.2 on 2024-03-27 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='can_be_advisor',
            field=models.BooleanField(default=False),
        ),
    ]
