# Generated by Django 4.2 on 2024-04-11 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_rename_gpa_student_gpa_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='gpa_student',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
    ]
