version: '3'

services:
  backend:
    build:
      context: ./back-end
    volumes:
      - ./back-end:/app
    expose:
      - "8000"
    depends_on:
      - db
      - rabbitmq
    env_file:
      - ./back-end/config/.env

  nginx:
    build:
      context: ./deployment/nginx
    ports:
      - "80:80"
    depends_on:
      - backend  # Changed from 'back-end' to 'backend'

  db:
    image: postgres
    env_file:
      - ./back-end/config/.env

  rabbitmq:
    image: rabbitmq:management
    ports:
      - "5672:5672"
      - "15672:15672"

  celery_worker:
    build:
      context: ./back-end
    command: celery -A your_project_name worker -l info
    volumes:
      - ./back-end:/app
    depends_on:
      - backend
      - rabbitmq
    env_file:
      - ./back-end/config/.env

  celery_beat:
    build:
      context: ./back-end
    command: celery -A config beat -l info
    volumes:
      - ./back-end:/app
    depends_on:
      - backend
      - rabbitmq
    env_file:
      - ./back-end/config/.env
