version: '3'

services:
  backend:
    build:
      context: ./backend
    volumes:
      - ./backend:/app
    expose:
      - "8000"
    depends_on:
      - db
      - rabbitmq
    env_file:
      - ./backend/.env

  nginx:
    build:
      context: ./deployment/nginx
    ports:
      - "80:80"
    depends_on:
      - backend

  db:
    image: postgres
    env_file:
      - ./backend/.env

  rabbitmq:
    image: rabbitmq:management
    ports:
      - "5672:5672"
      - "15672:15672"

  celery_worker:
    build:
      context: ./backend
    command: celery -A your_project_name worker -l info
    volumes:
      - ./backend:/app
    depends_on:
      - backend
      - rabbitmq
    env_file:
      - ./backend/.env

  celery_beat:
    build:
      context: ./backend
    command: celery -A your_project_name beat -l info
    volumes:
      - ./backend:/app
    depends_on:
      - backend
      - rabbitmq
    env_file:
      - ./backend/.env
