# Generated by Django 4.2 on 2024-03-28 22:44

import dashboard_student.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('education', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentDeleteSemesterRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_explanations', models.TextField()),
                ('result', models.CharField(max_length=100)),
                ('educational_assistant_explanation', models.TextField()),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='education.semestercourse')),
            ],
            bases=(models.Model, dashboard_student.models.BaseStudentRegistrationRequest),
        ),
        migrations.CreateModel(
            name='SemesterRegistrationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_courses', models.ManyToManyField(to='education.semestercourse', verbose_name='Requested_courses')),
            ],
            bases=(models.Model, dashboard_student.models.BaseStudentRegistrationRequest),
        ),
        migrations.CreateModel(
            name='RevisionRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('answer', models.TextField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='education.studentcourse')),
            ],
            bases=(models.Model, dashboard_student.models.BaseStudentRegistrationRequest),
        ),
        migrations.CreateModel(
            name='EnrollmentRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approval_status', models.CharField(choices=[('P', 'Pending'), ('A', 'Approved'), ('R', 'Rejected')], default='P', max_length=1)),
                ('reason_text', models.TextField()),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.teacher')),
            ],
            bases=(models.Model, dashboard_student.models.BaseStudentRegistrationRequest),
        ),
        migrations.CreateModel(
            name='EmploymentEducationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='education.semester')),
            ],
            bases=(models.Model, dashboard_student.models.BaseStudentRegistrationRequest),
        ),
        migrations.CreateModel(
            name='EmergencyRemovalRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_explanation', models.TextField()),
                ('educational_assistant_explanation', models.TextField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='education.studentcourse')),
            ],
            bases=(models.Model, dashboard_student.models.BaseStudentRegistrationRequest),
        ),
        migrations.CreateModel(
            name='AddRemoveRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_courses', models.ManyToManyField(related_name='added_courses', to='education.semestercourse')),
                ('removed_courses', models.ManyToManyField(related_name='removed_courses', to='education.studentcourse')),
            ],
            bases=(models.Model, dashboard_student.models.BaseStudentRegistrationRequest),
        ),
    ]
