# Generated by Django 4.2 on 2024-04-12 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_student', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='revisionrequest',
            name='score',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
    ]
