# Generated by Django 4.2 on 2024-03-28 11:09

import dashboard_student.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0007_alter_semesteraddremove_semester_and_more'),
        ('dashboard_student', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='semesterregistrationrequest',
            name='requested_courses',
        ),
        migrations.AddField(
            model_name='addremoverequest',
            name='semester',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='education.semester'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='semesterregistrationrequest',
            name='semester',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='education.semester'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='UnitSelectionRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_courses', models.ManyToManyField(to='education.semestercourse', verbose_name='Requested_courses')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='education.semester')),
            ],
        ),
    ]
