# Generated by Django 4.2 on 2024-04-12 19:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('education', '0001_initial'),
        ('dashboard_student', '0001_initial'),
        ('accounts', '__first__'),
    ]

    operations = [
        migrations.AddField(
            model_name='unitselectionrequest',
            name='request_course',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='unit_selection_request', to='education.semestercourse'),
        ),
        migrations.AddField(
            model_name='unitselectionrequest',
            name='semester_registration_request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dashboard_student.semesterregistrationrequest'),
        ),
        migrations.AddField(
            model_name='studentdeletesemesterrequest',
            name='semester_registration_request',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='dashboard_student.semesterregistrationrequest'),
        ),
        migrations.AddField(
            model_name='semesterregistrationrequest',
            name='requested_courses',
            field=models.ManyToManyField(blank=True, to='education.course', verbose_name='Requested_courses'),
        ),
        migrations.AddField(
            model_name='semesterregistrationrequest',
            name='semester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='education.semester'),
        ),
        migrations.AddField(
            model_name='semesterregistrationrequest',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.student'),
        ),
        migrations.AddField(
            model_name='revisionrequest',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='education.studentcourse'),
        ),
        migrations.AddField(
            model_name='revisionrequest',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.student'),
        ),
        migrations.AddField(
            model_name='queuedrequest',
            name='request_course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='education.semestercourse'),
        ),
        migrations.AddField(
            model_name='queuedrequest',
            name='semester_registration_request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dashboard_student.semesterregistrationrequest'),
        ),
        migrations.AddField(
            model_name='queuedrequest',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.student'),
        ),
        migrations.AddField(
            model_name='employmenteducationrequest',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.student'),
        ),
        migrations.AddField(
            model_name='emergencyremovalrequest',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='education.studentcourse'),
        ),
        migrations.AddField(
            model_name='emergencyremovalrequest',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.student'),
        ),
        migrations.AddField(
            model_name='addremoverequest',
            name='added_courses',
            field=models.ManyToManyField(blank=True, related_name='added_to_requests', to='education.semestercourse'),
        ),
        migrations.AddField(
            model_name='addremoverequest',
            name='removed_courses',
            field=models.ManyToManyField(blank=True, related_name='removed_from_requests', to='education.semestercourse'),
        ),
        migrations.AddField(
            model_name='addremoverequest',
            name='semester_registration_request',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='dashboard_student.semesterregistrationrequest'),
        ),
        migrations.AlterUniqueTogether(
            name='unitselectionrequest',
            unique_together={('semester_registration_request', 'request_course')},
        ),
    ]
