# Generated by Django 4.2 on 2024-04-11 10:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0001_initial'),
        ('accounts', '0002_initial'),
        ('dashboard_student', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='semesterregistrationrequest',
            name='semester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='education.semester'),
        ),
        migrations.AlterField(
            model_name='semesterregistrationrequest',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.student'),
        ),
    ]
