# Generated by Django 4.2 on 2024-04-11 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_student', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentdeletesemesterrequest',
            name='student',
        ),
    ]
