# Generated by Django 4.2 on 2024-03-25 14:18

import dashboard_student.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0004_alter_course_corequisite_alter_course_prerequisite'),
        ('dashboard_student', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enrollmentrequest',
            name='student',
        ),
        migrations.CreateModel(
            name='EmploymentEducationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='education.semester')),
            ],
            bases=(models.Model, dashboard_student.models.BaseStudentRegistrationRequest),
        ),
    ]
