# Generated by Django 4.2 on 2024-04-10 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_student', '0002_alter_revisionrequest_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unitselectionrequest',
            name='approval_status',
            field=models.CharField(choices=[('A', 'Registered'), ('R', 'Reserved'), ('C', 'NeedChange'), ('P', 'Approved')], max_length=1),
        ),
    ]
