# Generated by Django 4.2 on 2024-04-01 18:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0003_remove_semestercourse_class_days_and_more'),
        ('accounts', '0004_alter_adminuser_user'),
        ('dashboard_student', '0002_remove_addremoverequest_educational_assistant_visited_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employmenteducationrequest',
            name='need_for',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='addremoverequest',
            name='semester_registration_request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dashboard_student.semesterregistrationrequest'),
        ),
        migrations.AlterField(
            model_name='emergencyremovalrequest',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='education.studentcourse'),
        ),
        migrations.AlterField(
            model_name='enrollmentrequest',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.teacher'),
        ),
        migrations.AlterField(
            model_name='revisionrequest',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='education.studentcourse'),
        ),
        migrations.AlterField(
            model_name='studentdeletesemesterrequest',
            name='semester_registration_request',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard_student.semesterregistrationrequest'),
        ),
        migrations.AlterField(
            model_name='unitselectionrequest',
            name='semester_registration_request',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='dashboard_student.semesterregistrationrequest'),
        ),
    ]
