# Generated by Django 4.2 on 2024-04-10 03:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_student', '0002_remove_unitselectionrequest_reuest_course_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EnrollmentRequest',
        ),
    ]
