# Generated by Django 4.2 on 2024-04-11 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0001_initial'),
        ('dashboard_student', '0002_remove_studentdeletesemesterrequest_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unitselectionrequest',
            name='student',
        ),
        migrations.RemoveField(
            model_name='unitselectionrequest',
            name='request_course',
        ),
        migrations.AddField(
            model_name='unitselectionrequest',
            name='request_course',
            field=models.ManyToManyField(to='education.semestercourse'),
        ),
    ]
