# Generated by Django 4.2 on 2024-04-11 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0001_initial'),
        ('dashboard_student', '0003_remove_unitselectionrequest_student_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unitselectionrequest',
            name='request_course',
            field=models.ManyToManyField(blank=True, to='education.semestercourse'),
        ),
    ]
