# Generated by Django 4.2 on 2024-03-28 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_student', '0003_addremoverequest_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='semesterregistrationrequest',
            name='explanation',
            field=models.TextField(blank=True, null=True),
        ),
    ]
