# Generated by Django 4.2 on 2024-04-01 17:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0003_alter_studentcourse_status'),
        ('dashboard_student', '0003_employmenteducationrequest_need_for_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emergencyremovalrequest',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='education.studentcourse'),
        ),
        migrations.AlterField(
            model_name='studentdeletesemesterrequest',
            name='semester_registration_request',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='dashboard_student.semesterregistrationrequest'),
        ),
    ]
