# Generated by Django 4.2 on 2024-04-10 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_student', '0003_alter_unitselectionrequest_approval_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emergencyremovalrequest',
            name='educational_assistant_explanation',
        ),
    ]
