# Generated by Django 4.2 on 2024-04-02 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0005_alter_semester_name'),
        ('dashboard_student', '0004_alter_emergencyremovalrequest_course_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='semesterregistrationrequest',
            name='requested_courses',
            field=models.ManyToManyField(blank=True, to='education.semestercourse', verbose_name='Requested_courses'),
        ),
        migrations.AlterField(
            model_name='unitselectionrequest',
            name='requested_courses',
            field=models.ManyToManyField(blank=True, to='education.semestercourse', verbose_name='Requested_courses'),
        ),
    ]
