# Generated by Django 4.2 on 2024-04-03 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_student', '0005_semesterregistrationrequest_requested_courses_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='semesterregistrationrequest',
            name='student_comment_for_requested_courses',
            field=models.TextField(blank=True, null=True),
        ),
    ]
