# Generated by Django 4.2 on 2024-04-11 13:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
        ('dashboard_student', '0005_alter_unitselectionrequest_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentdeletesemesterrequest',
            name='student',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='accounts.student'),
        ),
    ]
