# Generated by Django 4.2 on 2024-04-10 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_student', '0005_alter_unitselectionrequest_approval_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentdeletesemesterrequest',
            name='educational_assistant_explanation',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='studentdeletesemesterrequest',
            name='student_explanations',
            field=models.TextField(blank=True, null=True),
        ),
    ]
