# Generated by Django 4.2 on 2024-04-04 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0005_alter_semester_name'),
        ('dashboard_student', '0006_semesterregistrationrequest_student_comment_for_requested_courses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='semesterregistrationrequest',
            name='requested_courses',
            field=models.ManyToManyField(blank=True, to='education.course', verbose_name='Requested_courses'),
        ),
    ]
