# Generated by Django 4.2 on 2024-03-21 09:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('education', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentRegistrationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.PositiveSmallIntegerField()),
                ('status', models.BooleanField(default=False)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.student')),
            ],
        ),
        migrations.CreateModel(
            name='StudentDeleteSemesterRequest',
            fields=[
                ('studentregistrationrequest_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='enrollment.studentregistrationrequest')),
                ('student_explanations', models.TextField()),
                ('result', models.CharField(max_length=100)),
                ('educational_assistant_explanation', models.TextField()),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='education.semestercourse')),
            ],
            bases=('enrollment.studentregistrationrequest',),
        ),
        migrations.CreateModel(
            name='SemesterRegistrationRequest',
            fields=[
                ('studentregistrationrequest_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='enrollment.studentregistrationrequest')),
                ('requested_courses', models.ManyToManyField(to='education.semestercourse', verbose_name='Requested_courses')),
            ],
            bases=('enrollment.studentregistrationrequest',),
        ),
        migrations.CreateModel(
            name='RevisionRequest',
            fields=[
                ('studentregistrationrequest_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='enrollment.studentregistrationrequest')),
                ('text', models.TextField()),
                ('answer', models.TextField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='education.semestercourse')),
            ],
            bases=('enrollment.studentregistrationrequest',),
        ),
        migrations.CreateModel(
            name='EmergencyRemovalRequest',
            fields=[
                ('studentregistrationrequest_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='enrollment.studentregistrationrequest')),
                ('student_explanation', models.TextField()),
                ('educational_assistant_explanation', models.TextField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='education.semestercourse')),
            ],
            bases=('enrollment.studentregistrationrequest',),
        ),
        migrations.CreateModel(
            name='AddRemoveRequest',
            fields=[
                ('studentregistrationrequest_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='enrollment.studentregistrationrequest')),
                ('added_courses', models.ManyToManyField(related_name='added_courses', to='education.semestercourse')),
                ('removed_courses', models.ManyToManyField(related_name='removed_courses', to='education.semestercourse')),
            ],
            bases=('enrollment.studentregistrationrequest',),
        ),
    ]
