# Generated by Django 4.2 on 2024-03-26 17:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentcourse',
            old_name='course',
            new_name='semester_course',
        ),
        migrations.AddField(
            model_name='course',
            name='department',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='education.department'),
            preserve_default=False,
        ),
    ]
