# Generated by Django 5.0.2 on 2024-03-29 17:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_student_gpa_and_more'),
        ('education', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentcourse',
            name='semester_course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='education.semestercourse'),
        ),
        migrations.AlterUniqueTogether(
            name='studentcourse',
            unique_together={('student', 'semester_course')},
        ),
    ]
