# Generated by Django 4.2 on 2024-04-10 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentcourse',
            name='status',
            field=models.CharField(choices=[('F', 'FinalRegistered'), ('R', 'Registered'), ('P', 'Pending'), ('W', 'Withdrawn'), ('D', 'Deleted'), ('E', 'EmergencyDelete'), ('S', 'DeleteSemester')], default='R', max_length=1),
        ),
    ]
