# Generated by Django 4.2 on 2024-04-01 18:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0002_alter_studentcourse_semester_course_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='semestercourse',
            name='class_days',
        ),
        migrations.AlterField(
            model_name='studentcourse',
            name='status',
            field=models.CharField(choices=[('F', 'FinalRegistered'), ('R', 'Registered'), ('P', 'Pending'), ('W', 'Withdrawn'), ('D', 'Deleted')], default='R', max_length=1),
        ),
        migrations.AddField(
            model_name='semestercourse',
            name='class_days',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
