# Generated by Django 4.2 on 2024-03-25 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0002_remove_prerequisite_course_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='corequisite',
            field=models.ManyToManyField(null=True, to='education.course'),
        ),
        migrations.AlterField(
            model_name='course',
            name='prerequisite',
            field=models.ManyToManyField(null=True, to='education.course'),
        ),
    ]
