# Generated by Django 4.2 on 2024-03-25 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0003_alter_course_corequisite_alter_course_prerequisite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='corequisite',
            field=models.ManyToManyField(to='education.course'),
        ),
        migrations.AlterField(
            model_name='course',
            name='prerequisite',
            field=models.ManyToManyField(to='education.course'),
        ),
    ]
