# Generated by Django 4.2 on 2024-04-01 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0003_remove_semestercourse_class_days_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='semestercourse',
            name='class_days',
        ),
        migrations.AddField(
            model_name='semestercourse',
            name='class_days',
            field=models.ManyToManyField(to='education.day'),
        ),
    ]
