# Generated by Django 4.2 on 2024-03-27 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0004_alter_semesterclass_semester'),
    ]

    operations = [
        migrations.AddField(
            model_name='semestercourse',
            name='corse_reserve_capasity',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='semestercourse',
            name='course_capacity',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
