# Generated by Django 4.2 on 2024-03-25 14:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_educationalassistant_department_and_more'),
        ('education', '0004_alter_course_corequisite_alter_course_prerequisite'),
    ]

    operations = [
        migrations.RenameField(
            model_name='semestercourse',
            old_name='class_capacity',
            new_name='course_capacity',
        ),
        migrations.RemoveField(
            model_name='semester',
            name='add_remove_end',
        ),
        migrations.RemoveField(
            model_name='semester',
            name='add_remove_start',
        ),
        migrations.RemoveField(
            model_name='semester',
            name='classes_end',
        ),
        migrations.RemoveField(
            model_name='semester',
            name='classes_start',
        ),
        migrations.RemoveField(
            model_name='semester',
            name='emergency_remove_end',
        ),
        migrations.RemoveField(
            model_name='semester',
            name='emergency_remove_start',
        ),
        migrations.RemoveField(
            model_name='semester',
            name='exam_end',
        ),
        migrations.RemoveField(
            model_name='semester',
            name='exam_start',
        ),
        migrations.RemoveField(
            model_name='semester',
            name='selection_end',
        ),
        migrations.RemoveField(
            model_name='semester',
            name='selection_start',
        ),
        migrations.AddField(
            model_name='semester',
            name='semester_type',
            field=models.CharField(choices=[('F', 'Fall'), ('W', 'Winter'), ('S', 'Summer')], default='F', max_length=1),
        ),
        migrations.AlterField(
            model_name='course',
            name='corequisite',
            field=models.ManyToManyField(related_name='corequisites', to='education.course'),
        ),
        migrations.AlterField(
            model_name='course',
            name='prerequisite',
            field=models.ManyToManyField(related_name='prerequisites', to='education.course'),
        ),
        migrations.AlterField(
            model_name='semestercourse',
            name='instructor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.teacher'),
        ),
        migrations.AlterField(
            model_name='studentcourse',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='education.semestercourse'),
        ),
        migrations.CreateModel(
            name='SemesterUnitSelection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_selection_start', models.DateField()),
                ('unit_selection_end', models.DateField()),
                ('semester', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='education.semester')),
            ],
        ),
        migrations.CreateModel(
            name='SemesterExam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_start', models.DateField()),
                ('exam_end', models.DateField()),
                ('semester', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='education.semester')),
            ],
        ),
        migrations.CreateModel(
            name='SemesterEmergency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emergency_remove_start', models.DateField()),
                ('emergency_remove_end', models.DateField()),
                ('semester', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='education.semester')),
            ],
        ),
        migrations.CreateModel(
            name='SemesterClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classes_start', models.DateField()),
                ('classes_end', models.DateField()),
                ('semester', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='education.semester')),
            ],
        ),
        migrations.CreateModel(
            name='SemesterAddRemove',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('addremove_start', models.DateField()),
                ('addremove_end', models.DateField()),
                ('semester', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='education.semester')),
            ],
        ),
    ]
