# Generated by Django 4.2 on 2024-03-26 14:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0005_rename_class_capacity_semestercourse_course_capacity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='department',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='education.department'),
            preserve_default=False,
        ),
    ]
