# Generated by Django 4.2 on 2024-03-28 10:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0005_semestercourse_corse_reserve_capasity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='semestercourse',
            name='corse_reserve_capasity',
        ),
        migrations.AlterField(
            model_name='semesteraddremove',
            name='semester',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='education.semester'),
        ),
        migrations.AlterField(
            model_name='semesterclass',
            name='semester',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='education.semester'),
        ),
        migrations.AlterField(
            model_name='semestercourse',
            name='course_capacity',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='semesteremergency',
            name='semester',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='education.semester'),
        ),
        migrations.AlterField(
            model_name='semesterexam',
            name='semester',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='education.semester'),
        ),
        migrations.AlterField(
            model_name='semesterunitselection',
            name='semester',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='education.semester'),
        ),
    ]
