# Generated by Django 4.2 on 2024-03-28 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0005_semestercourse_corse_reserve_capasity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='semester',
            name='end_semester',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='semester',
            name='start_semester',
            field=models.DateField(),
        ),
    ]
