# Generated by Django 4.2 on 2024-03-28 11:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0006_remove_semestercourse_corse_reserve_capasity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='semesteraddremove',
            name='semester',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='addremove', to='education.semester'),
        ),
        migrations.AlterField(
            model_name='semesterclass',
            name='semester',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='education.semester'),
        ),
        migrations.AlterField(
            model_name='semesteremergency',
            name='semester',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='emergency', to='education.semester'),
        ),
        migrations.AlterField(
            model_name='semesterexam',
            name='semester',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='exams', to='education.semester'),
        ),
        migrations.AlterField(
            model_name='semesterunitselection',
            name='semester',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='unit_selection', to='education.semester'),
        ),
    ]
